### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by tornadoblue**
Updates made for using environment variables for the subfolder and deploying to github pages when using "npm run deploy:test"

Production uses normal deploy, requires a deploy.sh to be created for copying files to the web server folder.

Images on the gallery page resized/renamed using ImageMagick batch processing to reduce file asset sizes.  This will help decrease the bandwidth used by the web hosting account and mobile/cell phone users data plans.

### CODE REVIEW

**Comment by tornadoblue** [comment]
Thanks Jordan.. Does it still deploy ok to your github page (
https://awfulvizz.github.io/reservoir_coffee ) when using "npm run
deploy:test" ?

Cheers
Reid

**Comment by JordanAbel** [comment]
I'll make a change and test it. It doesn't matter too much either way, I only had it deployed there as a way of showing Kristine the progress and to get feedback. Thanks for getting it hosted on prod by the way!

**Comment by tornadoblue** [comment]
Ah ok, I thought that it might not matter too much but wasn't sure if you
wanted to use it for further feedback...   https://surge.sh/  is also
pretty cool for quickly putting up static sites for review from the CLI.

And thanks for building the site for Kristine, it's cool that you used
React for the project.  I mostly use React + TypeScript / NodeJS for my
work projects these days.

-Reid

**Comment by JordanAbel** [comment]
Yeah I am doing an internship right now with an internet company and we are developing our web app using ReactJS for FE and Django for the BE API. I thought it would be beneficial to learn more about React by doing a project of my own.

Do I need your credentials to deploy to prod using surge? I was watching some of the video they have on their site and it was saying you have to create an account which will ensure you are the sole user deploying to the domain.

**Comment by tornadoblue** [comment]
> Do I need your credentials to deploy to prod using surge? I was watching some of the video they have on their site and it was saying you have to create an account which will ensure you are the sole user deploying to the domain.

Sorry, didn't see your question earlier...  

You can use your credentials to log into the surge.sh site and create API tokens and store your email and the token as env variables.   SURGE_LOGIN set to the email address you use with Surge and the token as SURGE_TOKEN
   
Then you don't need to enter credentials each time.

**Pull request merged**
